namespace ContaCorrente.Domain.Enums;

public enum ErrorType
{
    INVALID_DOCUMENT,
    USER_UNAUTHORIZED,
    INVALID_ACCOUNT,
    INACTIVE_ACCOUNT,
    INVALID_VALUE,
    INVALID_TYPE,
    INSUFFICIENT_BALANCE,
    INVALID_TOKEN,
    TOKEN_EXPIRED
}